version: V1.0

server:
  port: 8091
  servlet:
    session:
      timeout: 21600s
    contextPath: /api


oracle:
  spring:
    datasource:
      url: jdbc:oracle:thin:@localhost
      username: SEIBASOFTWARE
      password: 101
      driverClassName: oracle.jdbc.driver.OracleDriver
      type: com.zaxxer.hikari.HikariDataSource

spring:
  datasource:
    hikari:
      poolName: poolHikari