SELECT * FROM RESIDENTE
INNER JOIN APARTAMENTO ON RESIDENTE.ID_NUMERO_APARTAMENTO = APARTAMENTO.NUMERO_APARTAMENTO
INNER JOIN TIPO_DOCUMENTO ON RESIDENTE.TIPO_DOCUMENTO = TIPO_DOCUMENTO.ID_TIPO_DOCUMENTO
WHERE ID_RESIDENTE = :id