SELECT * FROM ENTREGA
INNER JOIN EMPLEADO_PROVEEDOR ON ENTREGA.ID_EMPLEADO_PROVEEDOR = EMPLEADO_PROVEEDOR.ID_EMPLEADO_PROVEEDOR
INNER JOIN RESIDENTE ON ENTREGA.ID_RESIDENTE = RESIDENTE.ID_RESIDENTE
INNER JOIN TIPO_PAQUETE ON ENTREGA.ID_TIPO_PAQUETE = TIPO_PAQUETE.ID_TIPO_PAQUETE